### ISSUE TITLE
go packages deprecated?

### ISSUE THREAD

**Issue by CatherineH** [arduino/arduino-builder#147]
The go packages x/tools/cmd/vet and x/codereview/patch seem to have been removed:

[https://godoc.org/golang.org/x/tools/cmd/vet](https://godoc.org/golang.org/x/tools/cmd/vet)
[https://godoc.org/golang.org/x/codereview/patch](https://godoc.org/golang.org/x/codereview/patch) 

Is there a workaround that doesn't use these packages?

**Comment by cmaglie** [comment]
`x/codereview/patch` has been used to apply patches dropped in `test/downloaded_stuff_patches` folder. Since there are no patches at the moment I disabled it, and removed the dependency.

If we will ever need `.patch` files in the future we'll find another implementation in that moment.

`golang.org/x/tools/cmd/vet` is no more a dependency since it's bundled in latest versions of go.
