### ISSUE TITLE
functional and memory error in ESP8266WiFiGeneric.h libarary

### ISSUE THREAD

**Issue by SayliCtron** [arduino/arduino-builder#224]
C:\Users\Administrator\Documents\Arduino\libraries\Arduino-master\Arduino-master\libraries\libraries\ESP8266WiFi\src/ESP8266WiFiGeneric.h:27:22: fatal error: functional: No such file or directory

 #include <functional>

Please help me to come out from this error

**Comment by per1234** [comment]
A few problems here:
- Since you didn't use code markup the important part of the error message was eaten by the Markdown renderer.
- The problem almost certainly is not related to arduino-builder.
- The problem is most likely caused by user error. Support requests should not be submitted to issue trackers. Instead please post your problem to the Arduino forum: http://forum.arduino.cc/index.php?board=11.0 and you'll surely have help very quickly.
