### ISSUE TITLE
User defined libraries

### ISSUE THREAD

**Issue by yash1112** [arduino/arduino-builder#237]
My arduino sketch has some user defined header files. arduino-builder is unable to compile the code if i provide location of those header file after -libraries  
It compiles the code only if all header files and sketch are in same directory.
Is there any way I can compile my code without putting header file in same directory?

**Comment by matthijskooijman** [comment]
The `-libraries` path is a path to a folder containing libraries, where each library is contained in a subfolder. Normally, you would create a proper Arduino library from your header files (with a `library.properties` file) and put those in a subdirectory of your Sketchbook/libraries directory (or whatever directory you pass to `-libraries`). At the very minimum, a library is just a directory containing header and source files, without any `library.properties` file, so that might work for you.

However, it sounds like you're trying to go off the beaten path and do more advanced things (like calling arduino-builder directly for some reason), but without really grasping how the Arduino compilation process works. I'd suggest googling a bit more (I don't have any links read) and looking closely at Arduino's verbose output, to better understand what's happening there.
