### ISSUE TITLE
Why is ctags incorrectly placed in released.

### ISSUE THREAD

**Issue by beriberikix** [arduino/arduino-builder#239]
Using the 1.3.25, at least on macos, the ctags is in the incorrect location. It is currently in `arduino-builder/tools/ctags/`alongside `5.8-arduino11` when it should be inside `5.8-arduino11`, as it is in the IDE .app. Things don't compile correctly otherwise. Any reason it is there?

**Comment by facchinm** [comment]
Hi @beriberikix ,
you are referring to the builder [release](https://github.com/arduino/arduino-builder/releases/tag/1.3.25) , right? The Java IDE extracts that archive during packaging and moves `ctags` binary to the correct location. Anyway, the location of the binary is totally arbitrary since you can specify it with `-tools` flag. Hope this is clear enough, feel free to comment again if I missed something :wink:
