### ISSUE TITLE
Change filename of cached core to bypass Windows length limitations

### ISSUE THREAD

**Issue by facchinm** [arduino/arduino-builder#284]
As reported on https://github.com/arduino/Arduino/issues/7902 , if a core has many build flags the cached core filename ends up being too long (more than 255 characters).
Two possible solutions:
- [adding an index file](https://github.com/arduino/Arduino/issues/7902#issuecomment-414263572) (containing all the needed information) (0% chance of clashing filenames)
- hashing the actual filename (with sha256 for example) and using the hash as filename (very low chance of name clashing)

**Comment by matthijskooijman** [comment]
A combination might also make sense: Use a hash to quickly locate a cached core, and put the full information in a file inside the cached core to verify. In the unlikely event of a hash conflict, this allows wiping the previous cache, rather than getting a broken build. Having such a file is a good idea in any case, since it allows a user to inspect a cached directory and see what it is for as well.

**Comment by JiriBilek** [comment]
Hi, just a comment to the hash collision threat. Having only a few hashed strings we can safely ignore it. See e.g. [http://preshing.com/20110504/hash-collision-probabilities/probabilities/](http://preshing.com/20110504/hash-collision-probabilities/)  (the table at the very bottom).
