### ISSUE TITLE
Builder is unable to find generic libraries for 3rd party boards

### ISSUE THREAD

**Issue by dberenguer** [arduino/arduino-builder#97]
Issue https://github.com/arduino/arduino-builder/issues/83 is not totally fixed. Using platform-generic libraries (under SKETCHES/libraries/) from 3rd-party boards does not work. Libraries cannot be found by the builder.

I tested the SWAP library:
https://github.com/panStamp/swap

with this example:
https://github.com/panStamp/swap/tree/master/examples/binouts

for panStamp NRG2 board:
http://panstamp.org/arduino/package_panstamp_index.json

**Comment by dberenguer** [comment]
Any on-going work regarding this issue? 1.6.8 is still showing the problem.

We're using IDE 1.6.5 in the meantime.

**Comment by matthijskooijman** [comment]
Turns out the fix that was applied only worked for includes directly from the main .ino file. When scanning the compiler error output for missing includes, it only looked at the first line. However, when the .ino file includes a .h file in the sketch, which again includes a .h file from a library, the output looks like:
```
In file included from /tmp/arduino_modified_sketch_815412/binouts.ino:52:0:
/tmp/arduino_build_static/sketch/regtable.h:31:22: fatal error: register.h: No such file or directory
```
So the error in the first line is not found. The fix is of course simple: Scan all lines instead of just the first. I'll prepare a PR in a minute.

**Comment by dberenguer** [comment]
Thanks @matthijskooijman!

Looking forward to testing the fix on the next release.
